volumes:
  php-fpm-sock:

services:
  nginx:
    container_name: laravel-nginx
    build: ./nginx/
    image: laravel-nginx
    ports:
      - '80:80'
    volumes:
      - ~/git/github/menta/dev_laravel:/var/www:delegated
      - php-fpm-sock:/var/run/php-fpm
    tty: true
    depends_on:
      - app
  app:
    container_name: laravel-app
    build: ./app/
    image: laravel-app
    volumes:
      - ~/git/github/menta/dev_laravel:/var/www:delegated
      - php-fpm-sock:/var/run/php-fpm
    tty: true
    depends_on:
      - db
      - redis
  db:
    container_name: laravel-db
    build: ./mysql/
    image: laravel-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DEBUG: 1
    volumes:
      - ./mysql/db_data:/var/lib/mysql
  redis:
    build: ./redis/
    container_name: laravel-redis
    image: laravel-redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis/db_data:/data